apiVersion: v1
kind: Secret
metadata:
  name : {{ item }}
  namespace: default
data:
{% for key, value in (lookup('file', './secrets/{{ item }}.yaml') | from_yaml).items() %}
    {{ key }}: {{ value | b64encode }}
{% endfor %}    
  
